/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#fff8ef",
        "surface-dim": "#e1d9cb",
        "surface-bright": "#fff8ef",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fbf3e4",
        "surface-container": "#f5edde",
        "surface-container-high": "#efe7d9",
        "surface-container-highest": "#e9e2d3",
        "on-surface": "#1e1b13",
        "on-surface-variant": "#56423e",
        "inverse-surface": "#343026",
        "inverse-on-surface": "#f8f0e1",
        "outline": "#89726d",
        "outline-variant": "#ddc0ba",
        "surface-tint": "#9f402d",
        "primary": "#9f402d",
        "on-primary": "#ffffff",
        "primary-container": "#e2725b",
        "on-primary-container": "#5a0d02",
        "inverse-primary": "#ffb4a5",
        "secondary": "#56642b",
        "on-secondary": "#ffffff",
        "secondary-container": "#d6e7a1",
        "on-secondary-container": "#5a682f",
        "tertiary": "#2a6292",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6497ca",
        "on-tertiary-container": "#002e4e",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fff8ef",
        "on-background": "#1e1b13",
        "surface-variant": "#e9e2d3",
      },
      fontFamily: {
        heading: ['Montserrat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'brutal-sm': '2px 2px 0px 0px rgba(30,27,19,1)',
        'brutal': '4px 4px 0px 0px rgba(30,27,19,1)',
        'brutal-lg': '8px 8px 0px 0px rgba(30,27,19,1)',
        'brutal-xl': '12px 12px 0px 0px rgba(30,27,19,1)',
      },
      borderWidth: {
        '3': '3px',
        '4': '4px',
      }
    },
  },
  plugins: [],
}
