export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_ITEM_DATE: "INVALID_ITEM_DATE",
  INVALID_ACTIVITY_CITY: "INVALID_ACTIVITY_CITY",
  INVALID_ITINERARY_ITEM: "INVALID_ITINERARY_ITEM",
  INVALID_TIME_FORMAT: "INVALID_TIME_FORMAT",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];